# Directories =======

SRC = "."
DIST = "../dist"

# Compilers =======

CC = "gcc"
CFLAGS = "-Wall"

OCAMLOPT = "ocamlopt"
OCAMLC = "ocamlc"
OCAMLFIND = "ocamlfind"
DYPGEN = "dypgen"

# Flags =======

DYPGEN_FLAGS = ""

# Files =======

PARSER_DYP = "#{SRC}/parser.dyp"

# Tasks =====================================

desc "Compile All"
task :all => [:generate_parser, :compile_all]

task :clean => [:clean_all]

desc "Clean All"
task :clean_all do
  s =
  ["rm -rf #{SRC}/*.mxo #{SRC}/*.mxi #{SRC}/*.o",
   "#{DIST}/* #{SRC}/*.extract_type #{SRC}/parser_temp.ml #{SRC}/parser.ml #{SRC}/lexer.mli"]
  sh "#{s.join(' ')}"
end

desc "Generate Parser with dypgen"
task :generate_parser do
  sh "#{DYPGEN} #{DYPGEN_FLAGS} #{PARSER_DYP}"
end

desc "Compile All"
task :compile_all do
  # TODO: implement
end